kahluaband/Homepage_BE_SpringBoot

- .gitignore
#3 환경세팅
> gitignore 파일 수정, 기존 *.yml 에서 docker-compose와 application 파일만으로 수정
> #3 Feat: modify gitignore file

- .github/workflows/github-actions.yml
> #3 
> .gitignore 파일 제외하고 github-actions.yml 파일 추가하였습니다
>
>
> #3 Feat: add github-action script

- .github/workflows/github-actions.yml
> #3 
> github-actions.yml 파일에서 jar 파일 빌드 명령어를 gradlew clean build -x로 수정하였습니다 
>
>
> #3 Feat: modify github-action script

- src/main/java/kahlua/KahluaProject/domain/ticket/Meeting.java
- src/main/java/kahlua/KahluaProject/domain/ticket/Participants.java
- src/main/java/kahlua/KahluaProject/domain/ticket/Ticket.java
- src/main/java/kahlua/KahluaProject/domain/ticket/Type.java
> ex) #9 
> 예매하기 도메인 완성 
> 신입생 티켓과 일반 티켓 도메인 합침
> 각 도메인 간의 관계가 잘 연결되어 있는지 확인부탁드립니다.
> #9 Feat: make ticket domain

- src/main/java/kahlua/KahluaProject/domain/BaseEntity.java
> Fix: BaseEntity 수정

- src/main/java/kahlua/KahluaProject/domain/ticket/Status.java
- src/main/java/kahlua/KahluaProject/domain/ticket/Ticket.java
> #9 Feat : add status column in ticket domain

- .github/workflows/github-actions.yml
>#3
> github action ssh 인증 과정에서 계속 오류 발생중,,,
>
>
> #3 Feat: modify github-actions.yml

- src/main/java/kahlua/KahluaProject/DemoApplication.java
> #3 
> created_at, updated_at 속성 적용시키기 위해 @EnableJpaAuditing 어노테이션 추가
>
>
> #3 Feat: add EnableJpaAuditing annotation

- src/main/java/kahlua/KahluaProject/controller/AdminController.java
- src/main/java/kahlua/KahluaProject/dto/response/ApplyItemResponse.java
- src/main/java/kahlua/KahluaProject/dto/response/ApplyListResponse.java
- src/main/java/kahlua/KahluaProject/service/ApplyService.java
> #17 
>  ### 어드민 - 지원하기 기능 ⤵️
✅ 지원서 list 조회 구현
✅ 지원서 상세정보 조회 구현
> #17 Feat: make admin-apply list & detail function

- src/main/java/kahlua/KahluaProject/controller/TicketController.java
- src/main/java/kahlua/KahluaProject/converter/TicketConverter.java
- src/main/java/kahlua/KahluaProject/domain/ticket/Participants.java
- src/main/java/kahlua/KahluaProject/domain/ticket/Ticket.java
- src/main/java/kahlua/KahluaProject/dto/request/ParticipantsCreateRequest.java
- src/main/java/kahlua/KahluaProject/dto/request/TicketCreateRequest.java
- src/main/java/kahlua/KahluaProject/dto/response/ParticipantsResponse.java
- src/main/java/kahlua/KahluaProject/dto/response/TicketCreateResponse.java
- src/main/java/kahlua/KahluaProject/dto/response/TicketGetResponse.java
- src/main/java/kahlua/KahluaProject/repository/ParticipantsRepository.java
- src/main/java/kahlua/KahluaProject/repository/TicketRepository.java
- src/main/java/kahlua/KahluaProject/service/TicketService.java
> #9 Feat: make ticket function (demo)

- .github/workflows/github-actions.yml
> #3 Feat: modify github action yml

- src/main/java/kahlua/KahluaProject/confg/SecurityConfig.java
> #16 Fix: authorize 경로 수정

- src/main/java/kahlua/KahluaProject/confg/SwaggerConfig.java
> #3 
> 스웨거 서버에 https://kahluaband.com 추가
> http url로 테스트할 경우 CORS 에러 발생
> 혹시 몰라서 http, https 중에 선택할 수 있도록 설정해씀
> #3 Feat: add https url on swagger

- src/main/java/kahlua/KahluaProject/confg/CorsMvcConfig.java
- src/main/java/kahlua/KahluaProject/confg/SecurityConfig.java
- src/main/java/kahlua/KahluaProject/controller/AdminController.java
- src/main/java/kahlua/KahluaProject/service/ApplyService.java
> Fix: 401 Error

- src/main/java/kahlua/KahluaProject/confg/SecurityConfig.java
- src/main/java/kahlua/KahluaProject/confg/SwaggerConfig.java
> #16 Fix: 서버 url - swagger url 같도록 설정

- src/main/java/kahlua/KahluaProject/confg/SecurityConfig.java
> Fix: cors에러

- src/main/java/kahlua/KahluaProject/controller/AdminController.java
- src/main/java/kahlua/KahluaProject/dto/response/TicketItemResponse.java
- src/main/java/kahlua/KahluaProject/dto/response/TicketListResponse.java
- src/main/java/kahlua/KahluaProject/repository/ParticipantsRepository.java
- src/main/java/kahlua/KahluaProject/repository/TicketRepository.java
- src/main/java/kahlua/KahluaProject/service/TicketService.java
> #21 
> 전체 티켓, 일반 티켓, 신입생 티켓으로 나눠 티켓 리스트 조회 기능을 구현해씀다
> AdminService 따로 만들지 않고 TicketService에 서비스 로직 추가했는데 지저분한 것 같으면 바꾸겠습니당
> #21 Feat: add admin ticket list get method

- src/main/java/kahlua/KahluaProject/domain/ticket/Ticket.java
> ex) #9 
> 일반 티켓인 경우 예매 직후 상태: WAIT, 신입생 티켓인 경우 예매 직후 상태: FINISH
> #9 Feat: modify freshman ticket status

- src/main/java/kahlua/KahluaProject/controller/AdminController.java
- src/main/java/kahlua/KahluaProject/dto/ticket/response/TicketItemResponse.java
- src/main/java/kahlua/KahluaProject/service/TicketService.java
> ex) #21 
> 어드민 예매자 리스트에서 참석자가 보이지 않아 참석자 정보를 볼 수 있도록 추가
> #21 Feat: add participants list in admin ticket list

- src/main/java/kahlua/KahluaProject/apipayload/code/status/ErrorStatus.java
- src/main/java/kahlua/KahluaProject/controller/AdminController.java
- src/main/java/kahlua/KahluaProject/controller/TicketController.java
- src/main/java/kahlua/KahluaProject/converter/TicketConverter.java
- src/main/java/kahlua/KahluaProject/domain/BaseEntity.java
- src/main/java/kahlua/KahluaProject/domain/ticket/Status.java
- src/main/java/kahlua/KahluaProject/domain/ticket/Ticket.java
- src/main/java/kahlua/KahluaProject/dto/apply/request/ApplyCreateRequest.java
- src/main/java/kahlua/KahluaProject/dto/ticket/request/ParticipantsCreateRequest.java
- src/main/java/kahlua/KahluaProject/dto/ticket/response/ParticipantsResponse.java
- src/main/java/kahlua/KahluaProject/dto/ticket/response/TicketCreateResponse.java
- src/main/java/kahlua/KahluaProject/dto/ticket/response/TicketGetResponse.java
- src/main/java/kahlua/KahluaProject/dto/ticket/response/TicketUpdateResponse.java
- src/main/java/kahlua/KahluaProject/dto/user/request/SignInRequest.java
- src/main/java/kahlua/KahluaProject/dto/user/request/SignUpRequest.java
- src/main/java/kahlua/KahluaProject/repository/TicketRepository.java
- src/main/java/kahlua/KahluaProject/service/TicketService.java
> ex) #9 
> 티켓 취소 요청, 취소 완료 기능(어드민) 추가
> 스웨거 설명 추가
> 티켓 조회 시 예약번호로 조회할 수 있도록 수정
> 티켓 취소 완료 시 deletedAt 필드가 업데이트 되도록 수정
> 티켓 취소 요청, 결제 완료로 수정 시에는 updatedAt 만 작동
> #9 Feat: add cancel request and complete functions in ticket

- src/main/java/kahlua/KahluaProject/domain/apply/Apply.java
- src/main/java/kahlua/KahluaProject/domain/apply/Major.java
- src/main/java/kahlua/KahluaProject/dto/apply/request/ApplyCreateRequest.java
- src/main/java/kahlua/KahluaProject/dto/apply/response/ApplyCreateResponse.java
- src/main/java/kahlua/KahluaProject/dto/apply/response/ApplyGetResponse.java
- src/main/java/kahlua/KahluaProject/dto/apply/response/ApplyItemResponse.java
> #1 
> 지원서 전공(major) 속성 타입 enum에서 string으로 변경
> #1 Refactor: change major type to string

- src/main/java/kahlua/KahluaProject/apipayload/code/status/ErrorStatus.java
- src/main/java/kahlua/KahluaProject/controller/AdminController.java
- src/main/java/kahlua/KahluaProject/controller/adminController/AdminApplyController.java
- src/main/java/kahlua/KahluaProject/controller/adminController/AdminTicketController.java
- src/main/java/kahlua/KahluaProject/repository/TicketRepository.java
- src/main/java/kahlua/KahluaProject/service/TicketService.java
> #21 
> 전체/일반/신입생 티켓 리스트 정렬 옵션 - 예매자 기준 정렬 구현
> 기본적으로 최신순 정렬되도록 수정
> 어드민 컨트롤러 패키지 리팩토링
> 예매자 이름 기준 말고 또 다른 정렬 기준 추가 가능하도록 메서드 작성했습니다
> 일단 기본 정렬 방식은 최신순으로 두고 결제 상태 순서 정렬도 구현하면 더 직관적일 것 같슴다
> 결제 상태를 어떤 순서로 관리자한테 보여주면 좋을지 고민고민중
> Admin ticket

- src/main/java/kahlua/KahluaProject/domain/BaseEntity.java
- src/main/java/kahlua/KahluaProject/domain/ticket/Ticket.java
- src/main/java/kahlua/KahluaProject/domain/user/Credential.java
- src/main/java/kahlua/KahluaProject/domain/user/User.java
- src/main/java/kahlua/KahluaProject/service/TicketService.java
> ex) #9 
> deletedAt 적용 방식 통일 위해 코드 수정
> #9 Fix: modify method to update deleted_at field

- src/main/java/kahlua/KahluaProject/dto/ticket/response/TicketItemResponse.java
- src/main/java/kahlua/KahluaProject/service/TicketService.java
> ex) #21 
> 신입생 티켓 조회 리스트에서 학번이 보이지 않고 있어서 추가했습니다.
> #21 Fix: add studentId response in freshman admin list

- src/main/java/kahlua/KahluaProject/domain/ticket/Ticket.java
- src/test/java/kahlua/KahluaProject/domain/ticket/TicketUtilTest.java
- src/test/java/kahlua/KahluaProject/domain/ticket/ticketDomainTest.java
> ex) #40 
> 티켓 예매하기 테스트 코드 작성
> 테스트 코드가 올바른 방향으로 작성되고 있는지 확인 부탁드립니다.
> #40 Test: make ticket test code

- .github/workflows/github-actions.yml
> #3 
> github-actions.yml 파일에서 가동 중인 컨테이너 종료 및 삭제하는 명령어
sudo docker-compose down으로 변경
> #3 Feat: modify workflow yml file

- src/main/java/kahlua/KahluaProject/controller/adminController/AdminApplyController.java
- src/main/java/kahlua/KahluaProject/converter/ApplyConverter.java
- src/main/java/kahlua/KahluaProject/dto/apply/response/ApplyAdminGetResponse.java
- src/main/java/kahlua/KahluaProject/service/ApplyService.java
> #17 
> 어드민 페이지 지원자 상세정보 조회 메서드 구현
> 기존 상세정보 조회 메서드랑 필요한 데이터가 살짝 달라서 따로 구현했습니당
> #17 Feat: add admin applicant get method

- src/main/java/kahlua/KahluaProject/config/WebConfig.java
> ex) #3
> reverse proxy 설정을 추가하면서 forward header filter 설정 추가
> #3 Feat: add forward header filter

- build.gradle
- src/main/java/kahlua/KahluaProject/config/QueryDslConfig.java
- src/main/java/kahlua/KahluaProject/controller/adminController/AdminTicketController.java
- src/main/java/kahlua/KahluaProject/repository/ticket/TicketCustomRepository.java
- src/main/java/kahlua/KahluaProject/repository/ticket/TicketCustomRepositoryImpl.java
- src/main/java/kahlua/KahluaProject/repository/ticket/TicketRepository.java
- src/main/java/kahlua/KahluaProject/service/TicketService.java
> #21 
> Query DSL 설정 추가
> 결제 상태에 따른 티켓 리스트 정렬, 같은 결제 상태에 대해서는 최신순 정렬 구현
> enum 타입 속성에 대한 커스텀 정렬을 어떻게 구현할까 고민하다가 Query DSL을 사용해봤어요
> 많이 안써봐서,,,이렇게 사용하는게 맞는지 봐주시요,,,
> 더 좋은 방법 있다면 알려주세용
> #21 Feat: add find all order by status method on ticket

- src/main/java/kahlua/KahluaProject/config/SecurityConfig.java
> #3 Fix: modify swagger url

- src/main/java/kahlua/KahluaProject/repository/ticket/TicketCustomRepository.java
- src/main/java/kahlua/KahluaProject/repository/ticket/TicketCustomRepositoryImpl.java
- src/main/java/kahlua/KahluaProject/service/TicketService.java
> ex) #21 
> 티켓 타입 별 결제 상태 기준 정렬 구현
> #21 Fix: add type filter on ticket

- src/main/java/kahlua/KahluaProject/controller/TicketController.java
> ex) #9 
> TicketController 단계에서 return 하는 방식의 통일성을 위해 ApiResponse에서 ResponseEntity 로 방법 변경
> #9 Fix: change response method apiresponse to response entity

- src/main/java/kahlua/KahluaProject/DemoApplication.java
> ex) #3
> docker compose 실행을 하면서 jpa 와 redis를 스캔하는 과정에서 오류가 발생하고 있어서 @EnableJpaRepository 를 추가하여 수정하였습니다.
> #3 Fix: resolve jpa redis repository scan

- src/main/java/kahlua/KahluaProject/DemoApplication.java
> ex) #3 
> @EnableJpaRepository 수정
> #3 Fix: fix DemoApplication jpa repository annotation

- src/main/java/kahlua/KahluaProject/config/CorsMvcConfig.java
- src/main/java/kahlua/KahluaProject/config/SecurityConfig.java
> Chore: 임시 프론트 주소 추가

- .github/workflows/github-actions.yml
> #3 
> github-action 이벤트 트리거 push에서 pull request가 merge될 때로 변경
> #3 Feat: change github-action trigger to pr-merge

- .github/workflows/github-actions.yml
> #3 
> event trigger pull_request_target으로 변경
> #3 Fix: change event trigger

- src/main/java/kahlua/KahluaProject/config/CorsMvcConfig.java
- src/main/java/kahlua/KahluaProject/config/SecurityConfig.java
> #3 
> cors allowed origin에 www 서브도메인 추가
> #3 Fix: fix CORS error

- build.gradle
- src/main/java/kahlua/KahluaProject/controller/adminController/AdminApplyController.java
- src/main/java/kahlua/KahluaProject/controller/adminController/AdminTicketController.java
- src/main/java/kahlua/KahluaProject/service/ExcelConvertService.java
> #64 
> 지원자 리스트 엑셀 파일 변환 구현
> 전체 티켓 리스트 엑셀 파일 변환 구현
> 다운로드 파일을 ApiResponse로 감싸서 result에 넣기가 애매해서 ResponseEntity 사용해서 body에 바로 넣어줬어
> 다운로드 파일 관련 응답 처리 방법 잘 아는 사람 알려줘,,,ㅠ^ㅠ
> #64 Feat: add list to excel method

- .github/workflows/github-actions.yml
> #3 
> github-actions.yml 파일 resources 디렉토리 생성 명령어 삭제
> #3 Fix: fix github-actions workflow

- .github/workflows/github-actions.yml
> #3 
> workflow 내부 불필요한 주석 제거
> #3 Refactor: remove unnecessary comment

- src/main/java/kahlua/KahluaProject/websocket/StompHandler.java
> #69 
> 인증로직 수정사항 StompHandler에 반영!!
> #69 Fix: 인증로직 수정사항 반영

- src/main/java/kahlua/KahluaProject/apipayload/code/status/ErrorStatus.java
- src/main/java/kahlua/KahluaProject/controller/PostController.java
- src/main/java/kahlua/KahluaProject/converter/PostConverter.java
- src/main/java/kahlua/KahluaProject/domain/post/Post.java
- src/main/java/kahlua/KahluaProject/domain/post/PostLikes.java
- src/main/java/kahlua/KahluaProject/dto/post/request/PostCreateRequest.java
- src/main/java/kahlua/KahluaProject/dto/post/response/PostGetResponse.java
- src/main/java/kahlua/KahluaProject/dto/post/response/PostImageGetResponse.java
- src/main/java/kahlua/KahluaProject/repository/post/PostLikesRepository.java
- src/main/java/kahlua/KahluaProject/repository/post/PostRepository.java
- src/main/java/kahlua/KahluaProject/service/PostService.java
> ex) #74 
> 좋아요 생성/취소 기능, 게시글 페이지 조회 기능 추가
>
> #74 Feat: create likes and viewing post functions

- src/main/java/kahlua/KahluaProject/apipayload/code/status/ErrorStatus.java
> #69 Fix: merge conflict 오류 해결

- src/main/java/kahlua/KahluaProject/controller/PostController.java
- src/main/java/kahlua/KahluaProject/converter/PostConverter.java
- src/main/java/kahlua/KahluaProject/domain/post/Post.java
- src/main/java/kahlua/KahluaProject/domain/post/PostType.java
- src/main/java/kahlua/KahluaProject/repository/post/PostRepository.java
- src/main/java/kahlua/KahluaProject/repository/post/PostRepositoryCustom.java
- src/main/java/kahlua/KahluaProject/repository/post/PostRepositoryImpl.java
- src/main/java/kahlua/KahluaProject/service/PostService.java
- #92 
- [Feat: 게시판 오프셋 페이지네이션](https://github.com/kahluaband/Homepage_BE_SpringBoot/commit/1187da1604eb1c614f65c52c7bb41b235dbbb9bb)
>
> Feat: 게시판 오프셋 페이지네이션

- src/main/java/kahlua/KahluaProject/websocket/StompHandler.java
> Fix: 웹 소켓 구독 url 변경

- src/main/java/kahlua/KahluaProject/converter/PostConverter.java
- src/main/java/kahlua/KahluaProject/dto/post/request/PostCreateRequest.java
- src/main/java/kahlua/KahluaProject/dto/post/response/PostCreateResponse.java
- src/main/java/kahlua/KahluaProject/service/PostService.java
> ex) #74 
> postType을 게시판 기능에 적용
> NOTICE 타입인 경우 admin 사용자만 게시글 작성가능하고, KAHLUA_TIME 타입인 경우 admin&kahlua 사용자가 게시글 작성 가능하도록 함
> #74 Feat: add postType in post service

- src/main/java/kahlua/KahluaProject/controller/MyPageController.java
- src/main/java/kahlua/KahluaProject/controller/ReservationController.java
> #69 
> 마이페이지 컨트롤러 생성 + 사용자 예약 조회/삭제 엔드포인트 통합
>
> #69 Refactor: 마이페이지 컨트롤러 생성

- src/main/java/kahlua/KahluaProject/controller/MyPageController.java
- src/main/java/kahlua/KahluaProject/repository/post/PostRepositoryCustom.java
- src/main/java/kahlua/KahluaProject/repository/post/PostRepositoryImpl.java
- src/main/java/kahlua/KahluaProject/service/PostService.java
> ex) #98 
> 마이페이지 내에서 내가 작성한 글 리스트 조회
> #98 Feat: create mypage mypost view list

- src/main/java/kahlua/KahluaProject/config/SwaggerConfig.java
> ex) #101 
>  swaggerconfig api 통신 url 수정
> #101 Fix: fix swagger server api

- src/main/java/kahlua/KahluaProject/dto/user/request/SignUpRequest.java
- src/main/java/kahlua/KahluaProject/dto/user/request/UserInfoRequest.java
> Fix: 일반로그인 가능하도록 수정

- src/main/java/kahlua/KahluaProject/controller/AuthController.java
- src/main/java/kahlua/KahluaProject/controller/UserController.java
- src/main/java/kahlua/KahluaProject/converter/UserConverter.java
- src/main/java/kahlua/KahluaProject/domain/user/User.java
- src/main/java/kahlua/KahluaProject/domain/user/UserType.java
- src/main/java/kahlua/KahluaProject/dto/user/request/SignUpRequest.java
- src/main/java/kahlua/KahluaProject/repository/UserRepository.java
- src/main/java/kahlua/KahluaProject/service/SocialLoginService.java
- src/main/java/kahlua/KahluaProject/service/UserService.java
> Fix: 소셜로그인 & 정보 입력 분리

- src/main/java/kahlua/KahluaProject/domain/user/User.java
- src/main/java/kahlua/KahluaProject/domain/user/UserType.java
- src/main/java/kahlua/KahluaProject/dto/user/request/SignUpRequest.java
- src/main/java/kahlua/KahluaProject/security/jwt/JwtProvider.java
- src/main/java/kahlua/KahluaProject/service/SocialLoginService.java
> Fix: 권한 설정 수정

- src/main/java/kahlua/KahluaProject/converter/CommentConverter.java
- src/main/java/kahlua/KahluaProject/dto/post/response/CommentsCreateResponse.java
- src/main/java/kahlua/KahluaProject/dto/post/response/CommentsListResponse.java
- src/main/java/kahlua/KahluaProject/service/CommentService.java
> ex) close #108
> 댓글 생성과 댓글 리스트 조회 생성시간 조회할 수 있도록 수정
> #108 Fix: fix comment create and comment list response

- src/main/java/kahlua/KahluaProject/converter/PostConverter.java
- src/main/java/kahlua/KahluaProject/dto/post/response/PostGetResponse.java
> #110 close
> create comments count in list
> #110 Feat: create comments count in list

- src/main/java/kahlua/KahluaProject/converter/CommentConverter.java
- src/main/java/kahlua/KahluaProject/dto/post/response/CommentsItemResponse.java
- src/main/java/kahlua/KahluaProject/dto/post/response/CommentsListResponse.java
- src/main/java/kahlua/KahluaProject/service/CommentService.java
>close #112 
> 댓글 리스트에 삭제 시간 조회 기능 추가
> #112 Fix: add deleted_at response in comments list

- src/main/java/kahlua/KahluaProject/repository/post/PostRepositoryImpl.java
> Fix: 페이징 정렬조건 추가

- src/main/java/kahlua/KahluaProject/controller/CommentController.java
- src/main/java/kahlua/KahluaProject/converter/CommentConverter.java
- src/main/java/kahlua/KahluaProject/domain/BaseEntity.java
- src/main/java/kahlua/KahluaProject/domain/post/Comment.java
- src/main/java/kahlua/KahluaProject/service/CommentService.java
> close #116 
> 댓글 삭제 시 실제로 리스트에서 제거되지 않고 deleted_at 필드만 변경되도록 수정
> #116 Fix: make to be able to search deleted comments

- src/main/java/kahlua/KahluaProject/controller/PostController.java
- src/main/java/kahlua/KahluaProject/converter/PostConverter.java
- src/main/java/kahlua/KahluaProject/domain/post/Post.java
- src/main/java/kahlua/KahluaProject/dto/post/request/PostCreateRequest.java
- src/main/java/kahlua/KahluaProject/dto/post/request/PostUpdateRequest.java
- src/main/java/kahlua/KahluaProject/dto/post/response/PostUpdateResponse.java
- src/main/java/kahlua/KahluaProject/service/PostService.java
> #74 
> 게시글 수정 기능 추가
> 게시글 생성과 수정 코드가 method 유형 제외하고는 모두 동일하다고 판단해서 PostCreateRequest, PostCreateResponse를 사용해서 update 코드를 만들었습니다. 다른 좋은 방법이 있다면 말씀해주세요!
> #74 Feat: add post update function

- src/main/java/kahlua/KahluaProject/converter/CommentConverter.java
> #120
> 댓글 리스트에서 댓글 생성 시간 조회 기능  추가
> #120 Fix: add createdAt in comment list

- src/main/java/kahlua/KahluaProject/domain/post/Post.java
- src/main/java/kahlua/KahluaProject/repository/PostImageRepository.java
- src/main/java/kahlua/KahluaProject/service/PostService.java
> #74 
> 이미지를 빈 배열로 넘겼을 때 사진 삭제가 안되는 문제점 수정
> #74 Fix: fix to remove when get empty list

- src/main/java/kahlua/KahluaProject/controller/ReservationController.java
- src/main/java/kahlua/KahluaProject/service/ReservationService.java
> #69 Fix: destination 변수명 수정

- src/main/java/kahlua/KahluaProject/apipayload/code/status/ErrorStatus.java
- src/main/java/kahlua/KahluaProject/repository/reservation/ReservationCustomRepository.java
- src/main/java/kahlua/KahluaProject/repository/reservation/ReservationCustomRepositoryImpl.java
- src/main/java/kahlua/KahluaProject/service/ReservationService.java
> #124 Feat: 예약 시간 중복 예외처리 로직 추가

- src/main/java/kahlua/KahluaProject/dto/reservation/response/ReservationResponse.java
> #129 Fix: 사용 시작 시간 JsonFormat 수정

- src/main/java/kahlua/KahluaProject/domain/user/User.java
- src/main/java/kahlua/KahluaProject/domain/user/UserType.java
> Fix: 대기/미승인 사용자 추가

- src/main/java/kahlua/KahluaProject/converter/PostConverter.java
- src/main/java/kahlua/KahluaProject/domain/post/Post.java
- src/main/java/kahlua/KahluaProject/dto/post/request/PostCreateRequest.java
- src/main/java/kahlua/KahluaProject/dto/post/response/PostGetResponse.java
- src/main/java/kahlua/KahluaProject/repository/post/PostRepositoryImpl.java
> close #132
> PostGetResponse에 postType 필드 추가
> postType을 null로 받을 수 있도록 필드 설정 변경
> postType을 null로 받을 경우 전체 게시판을 조회할 수 있도록 함
> #132 Fix: show postType field in PostGetResponse

- src/main/java/kahlua/KahluaProject/service/PerformanceService.java
> 날짜 검증 시 연산자를 잘못 써서 모든 공연 상태가 open으로 들어가서 수정하였다
>
> fix: 날짜검증 로직 수정

- src/main/java/kahlua/KahluaProject/controller/adminController/AdminTicketController.java
- src/main/java/kahlua/KahluaProject/service/TicketService.java
> ex) #150
> 원래 이번에 리팩토링하면서 겹치는 api가 있어 지웠으나 에러가 나서 다시 복구해뒀다.
>
> Fix: 연결해둔 api 보류 (#150)

- src/main/java/kahlua/KahluaProject/global/websocket/WebSocketEventListener.java
> Fix: 동방예약 웹소켓 에러 (#173)

- src/main/java/kahlua/KahluaProject/global/websocket/WebSocketEventListener.java
> Fix: 동방예약 웹소켓 에러(accessor에 date값 추가) (#173)

- src/main/java/kahlua/KahluaProject/service/MailService.java
- src/main/java/kahlua/KahluaProject/service/PerformanceService.java
- src/main/java/kahlua/KahluaProject/service/TicketService.java
> Hotfix: ticketservice에 mailcache 업데이트 추가
